### ISSUE TITLE
Separate Categories Stacking On Top Of One Another

### ISSUE THREAD

**Issue by matthewwoop** [yonahforst/react-native-emoji-picker#1]
Any why the the categories are encroaching on one another? The code I'm running is copy&pasted from the Example.js file on RN 0.28

![screen shot 2016-08-16 at 1 27 41 pm](https://cloud.githubusercontent.com/assets/11703376/17709013/61b54796-63b5-11e6-9aeb-1138ec16c966.png)

**Comment by yonahforst** [comment]
I'm able to reproduce this by downgrading to RN 0.28.0. (I don't have this issue on RN 0.30.0)

I played around a bit and my best guess is that it has something to do with the way RN <= 0.28.0 calculates the width of a view when the flex content wraps. The view doesn't seem to adjust it's width to include the wrapped items. You can see it by setting `overflow: hidden` :

``` js
  categoryInner: {
    flex: 1,
    flexWrap: 'wrap', 
    flexDirection: 'column',
    overflow: 'hidden',
  }
```
