### ISSUE TITLE
Design issue

### ISSUE THREAD

**Issue by krishbhattacharyya** [yonahforst/react-native-emoji-picker#5]
Hi,

I can not adjust the icon size. Icon looks cropped. Is there any way to adjust this. One more thing I want to customize the design with the more professional looks ( Like category heading ). I have changed emoji-fontSize: 50, does not change anything. How can I do this? Nice component, actually I need more css class to customize this. 

![screen](https://cloud.githubusercontent.com/assets/10433734/26237137/7998d00c-3c91-11e7-92b4-e75dc43f71cb.png)

I think text need some specific class- 

![screen2](https://cloud.githubusercontent.com/assets/10433734/26237494/fcdc968c-3c92-11e7-9896-476b1c01f557.png)

**Comment by didil** [comment]
+1 we're having the same icons cropping issue on android

**Comment by krishbhattacharyya** [comment]
@yonahforst  is there any solution?

**Comment by yonahforst** [comment]
@krishbhattacharyya @didil  - I'm not actively working on RN projects right now, but I'll be happy to merge any PR's if you guys figure out the issue. 

@krishbhattacharyya - same for additional styling! :)

**Comment by yonahforst** [comment]
addressed in #6
